baseURL               = "https://wsqing12580.github.io/kjnav"
languageCode          = "zh-CN"
title                 = "康静工作导航站"
theme                 = "kjnav"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"					# 站点静态文件保存目录


[params]
    author        = "康静"
    description   = "康静工作环境导航 | Hugo 主题"
    upload        = "assets/images/Wechat-Card.jpg"
#    upload        = "https://github.com/wsqing12580/kjnav/issues"  # 左侧导航栏的"网站提交"
#     about         = "https://shumlab.com/cookbook/webstack-hugo"	# 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/wsqing12580/kjnav"
    enablePreLoad = false					# 网站完全打开前预加载动画
    textPreLoad   = "康静工作导航"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = false                         		# 默认启用一言服务

[params.seo]    
    baiduhmid       = 'bbb34e49a4b53de6a78cb36217d8d922'	# 百度统计 hm.src 的 ID
    baiduSiteVer    = 'codeva-cCAOSG8MBO'			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/logo.png"
    searchImageL      = "assets/images/bg-bio.jpg"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-bio.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/logo.png"
    logoExpandDark    = "assets/images/logo.png"
    logoCollapseLight = "assets/images/logo.png"
    logoCollapseDark  = "assets/images/logo.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站导航主要用于工作书签，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱： awaken_admin@163.com <br/>&copy; 2022 - {year} By [WebStack-Hugo](https://github.com/wsqing12580/kjnav) | [qingsong 测试](https://www.qingsong.fun/) | [粤ICP备2022117061号](http://beian.miit.gov.cn/)<br/>'
